<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController; // Add this

// Authentication Routes (Generated by Breeze)
Route::middleware(['auth'])->group(function () {
    // Dashboard Route
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Company CRUD Routes
    Route::resource('companies', CompanyController::class);

    // Profile Route
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
});

// Default Redirect to Login
Route::get('/', function () {
    return redirect('/login');
});

// Breeze Authentication Routes
require __DIR__.'/auth.php';
